apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: local-dev
type: Opaque
data:
  # Base64 encoded values:
  # POSTGRES_USER: postgres
  # POSTGRES_PASSWORD: postgres
  # POSTGRES_DB: localmeadow
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: bG9jYWxtZWFkb3c=
